Repository Team-G25/frontend, pull requests merged in 2025-05, with the labels that each got.

#19 [Feat] 임시보관함 메일조회하기, 삭제하기 기능추가
  src/apis/mailWrite/sendMail.js
  src/apis/temporary/temporaryDrafts.js
  src/apis/temporary/writeDraft.js
  src/pages/mailTemporary/components/common/bottom/bottom1.jsx
  src/pages/mailTemporary/components/common/bottom/index.style.js
  src/pages/mailTemporary/components/common/deletePopuUp/deletePopUpModal.jsx
  src/pages/mailTemporary/components/common/deletePopuUp/index.style.js
  src/pages/mailTemporary/components/common/mailButton/index.style.js
  src/pages/mailTemporary/components/common/mailButton/mailBtn.jsx
  src/pages/mailTemporary/components/common/mailEditor/index.style.js
  src/pages/mailTemporary/components/common/mailEditor/mailEditorComponent.jsx
  src/pages/mailTemporary/components/common/submitCancelButton/index.style.js
  src/pages/mailTemporary/components/common/submitCancelButton/submitCancelBtn.jsx
  src/pages/mailTemporary/components/common/top/TopContent.jsx
  src/pages/mailTemporary/components/common/top/index.style.js
  src/pages/mailTemporary/components/common/topButton/index.style.js
  src/pages/mailTemporary/components/common/topButton/topBtn.jsx
  src/pages/mailTemporary/index.style.js
  src/pages/mailTemporary/mailTemporary.jsx
Labels: 🎈 Feat

#22 [Feat] AI 생성 메일 작성 기능 구현
  src/apis/saveMail.js
  src/components/common/presaveAlert/SaveAlertModal.jsx
  src/components/common/presaveAlert/index.style.js
  src/components/common/spinner/SpinnerComponent.jsx
  src/components/common/submitAlert/SubmitAlertModal.jsx
  src/components/common/submitAlert/index.style.js
  src/pages/mailAI/components/generationInput/AIGenerationInput.jsx
  src/pages/mailAI/components/mailEditor/MailEditorComponent.jsx
  src/pages/mailAI/components/mailEditor/index.style.js
  src/pages/mailAI/mailAI.jsx
  src/pages/mailTemplate/components/mailEditor/MailEditorComponent.jsx
  src/pages/mailTemporary/components/common/top/index.style.js
  src/pages/mailTemporary/mailTemporary.jsx
Labels: 🎈 Feat

#24 [Feat] 로그인 인증 로직 구현
  package.json
  src/App.jsx
  src/apis/aiMail/postGenerateMail.js
  src/apis/auth/user.js
  src/apis/instance.js
  src/components/common/sideBar/SideBarComponent.jsx
  src/components/common/sideBar/index.style.js
  src/hooks/.keep
  src/pages/auth/hooks/.keep
  src/pages/auth/login.jsx
  src/pages/auth/login.style.js
  src/pages/auth/store/userStore.js
  src/pages/auth/utils/authService.js
  src/pages/mailAI/components/generationInput/AIGenerationInput.jsx
  src/pages/mailAI/mailAI.jsx
  src/pages/mailTemporary/mailTemporary.jsx
  yarn.lock
Labels: 🎈 Feat

#25 [Feat] 로그인 로직 추가 구현
  src/components/common/sideBar/SideBarComponent.jsx
  src/pages/home.jsx
Labels: 🔧 Fix, 🎈 Feat

#23 [feat, design] 메일 에디터 크기 조정 및, 임시 저장기능 활성화
  src/apis/mailWrite/sendMail.js
  src/apis/saveMail.js
  src/apis/temporary/writeDraft.js
  src/pages/mailAI/components/mailEditor/MailEditorComponent.jsx
  src/pages/mailManually/components/common/manualEditor/index.style.js
  src/pages/mailManually/components/common/manualEditor/manualEditorComp.jsx
  src/pages/mailManually/index.style.js
  src/pages/mailTemplate/components/mailEditor/MailEditorComponent.jsx
  src/pages/mailTemporary/components/common/mailButton/index.style.js
  src/pages/mailTemporary/components/common/mailEditor/index.style.js
  src/pages/mailTemporary/components/common/mailEditor/mailEditorComponent.jsx
  src/pages/mailTemporary/index.style.js
  src/pages/mailTemporary/mailTemporary.jsx
Labels: 🎈 Feat, 🎨 Design
